### ISSUE TITLE
The app doesn't show any passwords.

### ISSUE THREAD

**Issue by MELVARDEV** [hegocre/NextcloudPasswords#103]
### Checklist

- [X] I am able to reproduce the bug with the latest version [here](https://github.com/hegocre/NextcloudPasswords/releases/latest).
- [X] I have checked and there are *no existing issues* - [open](https://github.com/hegocre/NextcloudPasswords/issues) or [closed](https://github.com/hegocre/NextcloudPasswords/issues?q=is%3Aissue+is%3Aclosed) - which report the same bug.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.

### Affected version

v1.0.8 and v1.0.9-DEBUG (29) from Github Actions

### Steps to reproduce the bug

1. Install the app
2. Login to the server and authorize the app
3. View password list in the app

### Expected behavior

The app should display passwords form my Nextcloud server.

### Actual behavior

The main "Passwords" tab screen is empty / shows no passwords ("No content here"). Though, the "Folders" tab does correctly show all folders from the server (although they all are empty upon entering them). 
If I press the "Add / +" button and add a password, the password is correctly added to the server, but doesn't appear in the app.

### Affected Android/Custom ROM version

Android 14 / LineageOS 21

### Additional information

- Both the iOS app and the browser extensions do work as expected.
- I'm logging in to the nextcloud instance via username/password
- The End to End Encryption in the Passwords app is NOT enabled on the server.

I apologize although I am not sure where would I find any relevant logs. I'd appreciate any guidance where to find them if necessary (or any other debug steps for that fact).

**Comment by hegocre** [comment]
Hello,

I'm sorry you are experiencing issues. Could you please open the debug version, make it refresh, and then go to About > Long press "Version" and send me the logs by mail? That would be great in order to debug the issue.

Thank you!

**Comment by MELVARDEV** [comment]
Hi again,
I apologize for the delay. I have sent you the logs to your email adress.

**Comment by hegocre** [comment]
Hello, thank you for your cooperation.

From what I am seeing, it looks like the password listing is timing out. Is there any chance you have a lot of passwords/a slow server? That could explain the problem.

Thank you!

**Comment by MELVARDEV** [comment]
There is indeed quite a lot of passwords, and for a comparison the iOS app needs about 9-10 seconds for the first initial sync including the favicons, and the web version of the app also takes up to 15 seconds to display all of them without any filters. 

I might look into optimizing the server itself or thinning the password database but in meantime both the extension and iOS app work fine. Is there perhaps a way to increase the timeout? 

The loading indicator goes away after more or less the same amout of time the iOS app takes to sync the passwords (~10s), so I assume it either times out just before finishing the request or something goes wrong after the request is finished?

The server logs the requests as 200 for the reference, not sure if it is useful.
```
172.18.0.1 - melvar [23/Apr/2024:15:22:37 +0000] "GET /index.php/apps/passwords/api/1.0/folder/list HTTP/1.1" 200 3897 "-" "okhttp/4.12.0"

172.18.0.1 - melvar [23/Apr/2024:15:22:37 +0000] "GET /index.php/apps/passwords/api/1.0/folder/list HTTP/1.1" 200 3895 "-" "okhttp/4.12.0"

172.18.0.1 - melvar [23/Apr/2024:15:22:22 +0000] "GET /index.php/apps/passwords/api/1.0/password/list HTTP/1.1" 200 110048 "-" "okhttp/4.12.0"

172.18.0.1 - melvar [23/Apr/2024:15:22:22 +0000] "GET /index.php/apps/passwords/api/1.0/password/list HTTP/1.1" 200 110048 "-" "okhttp/4.12.0"
```

**Comment by hegocre** [comment]
Yeah, that makes sense. The timeout was a little low, with just 15 seconds, so that's probably it. Thank you also for the logs, they help confirm what we thought, the request is working fine, but there is not enough time to get all the reply.

I've created a PR with an increased timeout of 30 seconds, should fix the issue, it would be great if you could test the version from the [corresponding action](https://github.com/hegocre/NextcloudPasswords/actions/runs/8805482131) and confirm it.

Cheers!

**Comment by MELVARDEV** [comment]
I tried the new build and I confirm that it indeed have loaded all passwords at first try, no issues whatsoever. That would be it i suppose, appreciate your help on this and I'm looking forward to the next release.

**Comment by hegocre** [comment]
That's good to hear!! Thank you for your help!
