### ISSUE TITLE
AutoFill does not work in some apps

### ISSUE THREAD

**Issue by ScoreUnder** [hegocre/NextcloudPasswords#106]
### Checklist

- [X] I am able to reproduce the bug with the latest version [here](https://github.com/hegocre/NextcloudPasswords/releases/latest).
- [X] I have checked and there are *no existing issues* - [open](https://github.com/hegocre/NextcloudPasswords/issues) or [closed](https://github.com/hegocre/NextcloudPasswords/issues?q=is%3Aissue+is%3Aclosed) - which report the same bug.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.

### Affected version

v1.0.8 (26)

### Steps to reproduce the bug

1. Install an app which triggers this behaviour (e.g. [Sainsbury's SmartShop](https://play.google.com/store/apps/details?id=com.sainsburys.ssa))
2. Go to the login screen
3. Try to use autofill

### Expected behavior

Autofill available in the keyboard, or as a popup in the app, or via the long-press menu, even if no passwords show up in the search by default (I will adjust the search terms in that case)

### Actual behavior

Autofill options do not appear in keyboard or popup, and long press autofill says "Contents can't be auto-filled"

### Affected Android/Custom ROM version

Android 14 / default Google Pixel ROM / build AP1A.240405.002

### Affected device model

Pixel 7a

### Additional information

This has happened in other apps but I don't remember which -- I'll add a few if necessary but Sainsbury's SmartShop should be enough to test with(?)

**Comment by hegocre** [comment]
Hello,

The problem is now fixed with the app that you provided as an example, and possibly with other apps that had issues. This normally happens because apps do not correctly advertise its field type nor do they provide hints, which forces developers to play guess.

It would be great if you could install the app generated by the Github Action and test if it works for you.

Thank you!

**Comment by hegocre** [comment]
Closing this issue since I have obtained no response for weeks. Please, reopen if issues persist. Thank you!

**Comment by ScoreUnder** [comment]
Hi, sorry that this one slipped through the cracks, unfortunately I've tested it and it seems to be behaving the same as before the patch: 

![Screenshot_20240428-192740.png](https://github.com/hegocre/NextcloudPasswords/assets/1123686/dd2ebfbd-54d6-4e85-84d7-7d9ee0271b00)

![Screenshot_20240428-192813.png](https://github.com/hegocre/NextcloudPasswords/assets/1123686/722eef51-a28f-4c1d-8423-d2015f45d050)

**Comment by hegocre** [comment]
Hi,

I have checked again, and it works in the app you are showing. Please, try with the apk from [this](https://github.com/hegocre/NextcloudPasswords/actions/runs/8869356655) run and check again. There were several actions with version 29, some of which didn't have it fixed. This is version 30 and has it fixed, just tested it myself.

Thank you!

**Comment by ScoreUnder** [comment]
Given it a try and it is now working for me, thank you for looking at this
