### ISSUE TITLE
Cannot copy text from Notes field

### ISSUE THREAD

**Issue by TtuxX** [hegocre/NextcloudPasswords#119]
### Checklist

- [X] I am able to reproduce the bug with the latest version [here](https://github.com/hegocre/NextcloudPasswords/releases/latest).
- [X] I have checked and there are *no existing issues* - [open](https://github.com/hegocre/NextcloudPasswords/issues) or [closed](https://github.com/hegocre/NextcloudPasswords/issues?q=is%3Aissue+is%3Aclosed) - which report the same bug.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.

### Affected version

v1.0.9

### Steps to reproduce the bug

1. Open a password
2. Try to select text from the Notes field
3. Realise it's not possible
4. You then must have to edit the note to be able to select and copy the text from the Notes field

### Expected behavior

I would love to be able to select and copy text without having to edit a password 

### Actual behavior

I cannot select and copy text from the Notes field without having to edit the password 

### Affected Android/Custom ROM version

GrapheneOS Android 14

### Affected device model

Pixel 8

**Comment by hegocre** [comment]
Hello,

sorry for the delay answering this. Should be easy to implement, will do it as soon as I have some time.

Thank you!
