### ISSUE TITLE
Passwords with multiple custom fields with the same name crash the app

### ISSUE THREAD

**Issue by Popkornium18** [hegocre/NextcloudPasswords#21]
### Checklist

- [X] I am able to reproduce the bug with the latest version [here](https://github.com/hegocre/NextcloudPasswords/releases/latest).
- [X] I have checked and there are *no existing issues* - [open](https://github.com/hegocre/NextcloudPasswords/issues) or [closed](https://github.com/hegocre/NextcloudPasswords/issues?q=is%3Aissue+is%3Aclosed) - which report the same bug.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.

### Affected version

1.0.3

### Steps to reproduce the bug

I have a relatively complex entry with 6 extra websites and 1 additional secret. Opening this entry crashes the app every time.

I couldn't find out what actually causes the problem. I tried removing extra data one by one and eventually I would be able to open it, but I couldn't figure out what actually causes the problem.

### Expected behavior

The entry opens like any other

### Actual behavior

it crashes

### Affected Android/Custom ROM version

Latest LineageOS from microg

### Affected device model

Fairphone 4

**Comment by hegocre** [comment]
Hello, and thank you for your feedback! I'm going to try to reproduce the error, and see if I can grab some logs in order to debug the error. I'll get back to you as soon as possible.

**Comment by Saijin-Naib** [comment]
Is there a way I can share with you one specific one that crashes the app 100% of the time in a safe way?

**Comment by hegocre** [comment]
Hello, it would be great to have it, I haven't been able to reproduce it yet. The best way I can think of would be to export a CSV with all the passwords, edit it to leave only the desired password, and then email it to me at nextcloudpasswords@hegocre.com

And just to clarify. Does the crash occur when editing the password, or when viewing it?

Thank you

**Comment by Saijin-Naib** [comment]
I have only tested tapping it to view, but I think it would happen during trying to use the password from the password manager, as well.

**Comment by hegocre** [comment]
Hello @Saijin-Naib 

Any chance you can share the password? I've been trying to reproduce the crash by adding various passwords with up to 12 fields, and still no crash, which makes me think it could be another thing apart from the size which is triggering the crash. @Popkornium18 do you have more information that could be useful as well?

Thank you both!

**Comment by Saijin-Naib** [comment]
Yes, I'll send it over today

**Comment by Saijin-Naib** [comment]
Password sent, thanks so much for taking a look!

The WebUI on NextCloud does not seem bothered by this password, if that is helpful at all.

**Comment by hegocre** [comment]
Hi @Saijin-Naib 

Thanks to your help, I've managed to find the problem. It seems like it didn't occur to me that custom fields could have the same name, which apparently doesn't go too well with the way I handle custom fields.

I will rethink that so that it doesn't cause any problem

**Comment by hegocre** [comment]
Hi

Could you confirm that the [last generated app version](https://github.com/hegocre/NextcloudPasswords/actions/runs/6848345755) fixes the issue for you?

Thanks!!

**Comment by Popkornium18** [comment]
It does work, thanks.

**Comment by Saijin-Naib** [comment]
Still getting a crash here 😬

**Comment by hegocre** [comment]
With the password you sent me? In that case, before I go crazy, please check you are using the latest build from CI :pray:

**Comment by Saijin-Naib** [comment]
Crash with CI 75 and CI 76 upgraded from CI 75.

Works fine with reset and uninstall of CI 76 and fresh setup.

Looks like a migration that is needed didn't work for the database format?

**Comment by hegocre** [comment]
Hmmm, that's what I'd think, except there are no changes in the database, so no migrations should be needed.

Also, were you able to update from CI75 to CI76 directly? If I'm not mistaken, it shouldn't let you because of a signature mismatch between CI builds.

**Comment by Saijin-Naib** [comment]
Android 10 said it installed CI 76, but to be honest I didn't check the app build ID in app so I can't tell you for certain. I apologize for not checking more thoroughly.

**Comment by Popkornium18** [comment]
I just installed the ci build you linked in addition to the version I installed with obtainium and it worked.

**Comment by hegocre** [comment]
Hello,

I am glad to inform you that a new release has been published with the fix to this issue, along with some other fixes and improvements. You can download it from Google Play and GitHub.

Thank you one more time for your valuable feedback!

**Comment by Saijin-Naib** [comment]
Dude, thank you for the incredible responsiveness!

I can now continue to move my family over to my NextCloud and replace their password managers.
