### ISSUE TITLE
Feature Request: Draw Over Other Apps Permission

### ISSUE THREAD

**Issue by Saijin-Naib** [hegocre/NextcloudPasswords#23]
I'm having trouble on my Android 10 device with NextCloud Passwords prompts clearing and resetting when I'm trying to interact with them.

I'm seeing most other password managers request this permission, so I'm wondering if this would not help this behavior.

**Comment by hegocre** [comment]
Hello @Saijin-Naib 

Which prompts are you referring to? The ones related to autofill requests, like this:

![Screenshot_20231111-195325](https://github.com/hegocre/NextcloudPasswords/assets/15657088/fb1f664f-126d-48d9-ab15-94733acfe4b8)

Thanks for your feedback!

**Comment by Saijin-Naib** [comment]
Yes! These ones seem to clear, reset, disappear, etc when my keyboard comes out or I scroll, seemingly.

Sometimes they just flicker out, maybe by the website running scripts in the background?

**Comment by hegocre** [comment]
I'm merging this issue with #22, since the two features are related and, in the example of Bitwarden, work together.
