### ISSUE TITLE
Setting start view to anything other than passwords leads to inconvenient workflow

### ISSUE THREAD

**Issue by Popkornium18** [hegocre/NextcloudPasswords#25]
### Checklist

- [X] I am able to reproduce the bug with the latest version [here](https://github.com/hegocre/NextcloudPasswords/releases/latest).
- [X] I have checked and there are *no existing issues* - [open](https://github.com/hegocre/NextcloudPasswords/issues) or [closed](https://github.com/hegocre/NextcloudPasswords/issues?q=is%3Aissue+is%3Aclosed) - which report the same bug.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.

### Affected version

1.0.3

### Steps to reproduce the bug

- Set start view to folders
- Use the autofill service on some website
- The hostname is automatically put into the search bar

### Expected behavior

- Matching passwords are found

### Actual behavior

- Nothing is found, because the search will only search the folder names
- you have to go back to the passwords view and manually search

### Additional information

Maybe not strictly a bug, but definitely a usability flaw.
IMO the search should always search all passwords. That's what I would expect to happen.

**Comment by hegocre** [comment]
Hey @Popkornium18 

Thank you again for your feedback. You are right, I think I would also think the same, but given that I always use the All Passwords view, it didn't occur to me. I'm definitely making the change!
