### ISSUE TITLE
Feature Request: On-Screen Icon For Vault Password Setup 

### ISSUE THREAD

**Issue by Saijin-Naib** [hegocre/NextcloudPasswords#33]
I just accidentally cleared the Vault Password Setup dialog switching between apps, and it was not immediately obvious how to get back to doing it (close/re-open app).

Having an alert icon, maybe on the title bar, would be a great way to hand-hold people through interrupted setup.

Could also be a way to allow folks to change the Vault Password after initial setup without using the desktop site.

**Comment by hegocre** [comment]
Hi, I modified the dialog on #34, and now it cannot be dismissed, which means it will stay on top until you submit a password.

About the ability to change the password, I don't know if that's a good idea. It is not a procedure done so often, so being able to do it from the Web interface should suffice, taking into account that you can also do it from an Android web browser. Moreover, the documentation is not so clear on how to do this, and I am not willing to risk it and break my (or worse, somebody else's) database.
