### ISSUE TITLE
Feature Request: Biometric Authentication

### ISSUE THREAD

**Issue by Popkornium18** [hegocre/NextcloudPasswords#50]
### Checklist

- [X] I have checked and there are *no existing issues* - [open](https://github.com/hegocre/NextcloudPasswords/issues) or [closed](https://github.com/hegocre/NextcloudPasswords/issues?q=is%3Aissue+is%3Aclosed) - which request the same feature.
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.

### Feature description

It would be great if the app would allow using the biometric authentication that is already configured on the device.

### Why do you want this feature?

Biometric authentication offers good-ish security while requiring no "mental effort". If a user doesn't want to use an extra PIN it is much better to use biometric authentication then using none at all.

**Comment by hegocre** [comment]
Hello @Popkornium18,

Biometric authentication is already implemented in the app, but it is hidden until you enable PIN authentication. Maybe that's a little confusing? All the apps that I've seen using biometric auth require a PIN to be set, but maybe the option should be visible but disabled? 🤔

What do you think?

**Comment by Popkornium18** [comment]
Ah, I see. Nice! I think the best solution would be to show both options and to setup the pin first when biometric is used. If a pin is already present this would be skipped and just the biometric auth would be added. Afterwards both would be shown as activated. Disabling the pin shouldn't be possible without also disabling biometric.

**Comment by Popkornium18** [comment]
Awesome, thanks!
