### ISSUE TITLE
Autofill: URL search is too strict

### ISSUE THREAD

**Issue by TtuxX** [hegocre/NextcloudPasswords#51]
### Checklist

- [X] I am able to reproduce the bug with the latest version [here](https://github.com/hegocre/NextcloudPasswords/releases/latest).
- [X] I have checked and there are *no existing issues* - [open](https://github.com/hegocre/NextcloudPasswords/issues) or [closed](https://github.com/hegocre/NextcloudPasswords/issues?q=is%3Aissue+is%3Aclosed) - which report the same bug.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.

### Affected version

1.0.6

### Steps to reproduce the bug

1. Enable Autofill service
2. Go to some website for which you have some passwords saved
3. Try to fill the login form. The search opens up and tries to look your database for the exact URL of the page you are on
4. If domain has slightly changed (www3. something instead of www. for example), your password is not found as the search is too scrict

### Expected behavior

Less strict Autofill search.
Ideally, the app would trim the www. part and the domain extension part, and only look for the middle string of the domain name.
Or have a fuzzy search.

### Actual behavior

No password is found and I cannot login on the website 

### Additional information

Thank you very much for your awesome and extremely promising app!!!! 🎉 ❤️
I just discovered/installed it, looking forward to using it hundreds of times a day!!

**Comment by TtuxX** [comment]
Great, many thanks! 
Would it however also work for a specific case where the website domain change often to avoid DNS bans, but I don't always have time to systematically update the URL saved in the password entry?

**Comment by hegocre** [comment]
What do you mean by the domain extension? Do you mean the Top Level Domain (ex: .com, .net, ...)?

**Comment by hegocre** [comment]
Hmm, I think that would be quite a security risk. Say an attacker wants to harvest your facebook credentials, so he sets up a phishing site at facebook[.]io. Users may not even realize they are being phished, since the app autocompleted the autofill request as if it was a legitimate domain. I think I will not implement it, since I find it a risky idea. Other nextcloud apps and browser extensions don't allow this either, and I believe it is for good.
