### ISSUE TITLE
Add a Changelog on Github and in the App

### ISSUE THREAD

**Issue by TtuxX** [hegocre/NextcloudPasswords#55]
### Checklist

- [X] I have checked and there are *no existing issues* - [open](https://github.com/hegocre/NextcloudPasswords/issues) or [closed](https://github.com/hegocre/NextcloudPasswords/issues?q=is%3Aissue+is%3Aclosed) - which request the same feature.
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.

### Feature description

I would love to see a Changelog on Github and inside the App.

Tha Changelog could be a bit like this:
https://github.com/nextcloud/desktop/blob/master/CHANGELOG.md

Ideally, upon update, the App would show a pop-up with the Changelog and the changes since previously installed app version.
Furthermore, but this is another topic, this pop-up could also be used to show and highlight "Donate" button :)

### Why do you want this feature?

User cannot fully enjoy the new changes when there is an app update as he it not aware of them (no changelog on Github apart from digging into the commits).

**Comment by hegocre** [comment]
Hello!

You can find the changelog on the [releases tab](https://github.com/hegocre/NextcloudPasswords/releases), as well as in the [fastlane changelog directory](https://github.com/hegocre/NextcloudPasswords/tree/main/fastlane/metadata/android/en-US/changelogs) (although that might be more oriented to machines), as well as in Google Play.

I think we can simply add a changelog link in the about section, as well as a donate button.

**Comment by TtuxX** [comment]
Ah, my bad
Great, thank you very much!
