### ISSUE TITLE
I am a beginner and don't know how to make a nextcloud server or what it even is.

### ISSUE THREAD

**Issue by BloxyYT** [hegocre/NextcloudPasswords#63]
According to the title, I would like to know what a nextcloud server is and basic usage instructions.
I am very interested in using this app since it has a very clean material you design (and I dig that) and I also love that it's free!
So please explain to me how to use it.
Thank you.

(P.S. Can you import and export passwords? (Example: GooglePasswords.csv))

**Comment by Saijin-Naib** [comment]
I use a hosted VPS from Tab.Digital. 

Do a bit of reading up on your options and maybe revisit a password manager after you are a bit more familiar with the ecosystem and if it will fit your needs.

**Comment by BloxyYT** [comment]
> I use a hosted VPS from Tab.Digital. 
> 
> Do a bit of reading up on your options and maybe revisit a password manager after you are a bit more familiar with the ecosystem and if it will fit your needs. 

No, I meant what what is a nextcloud server?
But thanks for the suggestion :)

**Comment by TtuxX** [comment]
Hmm... not certain whether this is the right place to tackle such large questions 🤔 

**What is Nextcloud:**
https://nextcloud.com/

**Getting a Nextcloud instance while being a beginner:**
https://nextcloud.com/sign-up/ 

**How to setup a Nextcloud instance by yourself in a nutshell:**
https://www.digitalocean.com/community/tutorials/how-to-install-and-configure-nextcloud-on-ubuntu-20-04

**Comment by hegocre** [comment]
Thank you @TtuxX @Saijin-Naib for your contributions.

As commented above, this is not really the place to discuss what is Nextcloud.

However, before closing the issue, I'm going to add some information to the already provided one.

To sum up, I like to think of Nextcloud as a "Google Workspace", that is, a file hosting, calendar and contacts service, etc... It is also open source, which means you can install it on a server you own and manage it yourself, although that is not necessary.

In case you need more information, here are some links that might help:

* Nextcloud install documentation, in case you want to self-host: https://docs.nextcloud.com/server/latest/admin_manual/installation/index.html
* A list of NextCloud providers, both free and paid, in case you want someone else to manage it: https://github.com/nextcloud/providers (note that if you want to use the passwords app, you must make sure it is either available, or you can install custom apps)
* Also, in case you have some doubts, there is a great community of people that use nextcloud and self-host apps on reddit, you should check them out! https://www.reddit.com/r/selfhosted/ - https://www.reddit.com/r/NextCloud/
