### ISSUE TITLE
Possible Bug: PIN Pad does not reflow in Landscape Orientation

### ISSUE THREAD

**Issue by Saijin-Naib** [hegocre/NextcloudPasswords#76]
When inputting the PIN, one must be in Portrait otherwise none but the top three number buttons are accessible. 

Ideally, this would reflow to be usable no matter the orientation. 

![Screenshot_20240102-181430](https://github.com/hegocre/NextcloudPasswords/assets/19295950/d3b46152-4bc6-44a9-bea4-3c952c6cb6d6)

**Comment by SteveCaruso** [comment]
Similar problem on small screens. 

I'm running Nextcloud Passwords on a Lemfo APPLLP 4 Pro which is a round-panel 400x400 screen, and only the first row of pin buttons are visible.

**Comment by hegocre** [comment]
Hello,

I've created a pull request with a fix for this. It would be great if you could both test the new version and see if it is fixed, specially you @SteveCaruso with the round panel, which I don't have, so I cannot test.

Thank you!

**Comment by SteveCaruso** [comment]
Once it hits F-Droid I'll report back. :-)

**Comment by hegocre** [comment]
Would it be possible for you to test the latest APK from the Actions tab corresponding to this PR? That would help publish an APK which we make sure it fixes the problem.

The app in the actions tab is the latest version compiled from the source code of the last commit, which means the APK file comes from the code published on this repo.

You can download it from the artifacts section on [this page](https://github.com/hegocre/NextcloudPasswords/actions/runs/7777365005) (https://github.com/hegocre/NextcloudPasswords/actions/runs/7777365005).

Thank you very much!

**Comment by SteveCaruso** [comment]
I had to finagle it (the screen size and watch interface makes it tricky to navigate GitHub) but I managed to get it running and I can confirm it works perfectly now. :-)

![passcode works](https://github.com/hegocre/NextcloudPasswords/assets/20878276/aeacf769-649e-4a5b-8329-01b57b5839fb)

Thank you!

**Comment by Saijin-Naib** [comment]
Reflows right-aligned for me, but totally usable! 

Thanks!

**Comment by hegocre** [comment]
@SteveCaruso That's nice to hear, thank you!
@Saijin-Naib what do you mean? On lanscape orientations, it should appear in two columns, one for the text + dot indicators and one for the keypad, and all should be center-aligned within its column. Is that how it appears to you?

Thank you both!
