### ISSUE TITLE
Autofill sometimes not working in Samsung Internet

### ISSUE THREAD

**Issue by JannikWilhelm** [hegocre/NextcloudPasswords#83]
### Checklist

- [X] I am able to reproduce the bug with the latest version [here](https://github.com/hegocre/NextcloudPasswords/releases/latest).
- [X] I have checked and there are *no existing issues* - [open](https://github.com/hegocre/NextcloudPasswords/issues) or [closed](https://github.com/hegocre/NextcloudPasswords/issues?q=is%3Aissue+is%3Aclosed) - which report the same bug.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.

### Affected version

v1.0.7 (25)

### Steps to reproduce the bug

1. Open any website login page using Samsung Internet
2. when clicking the Username or password field, the autofill option should show up, but does not
3. Using another Browser (e.g. Chrome or Firefox), the autofill service comes up correctly

### Expected behavior

Using Samsung Internet, the autofill Option should be available too

### Affected Android/Custom ROM version

Android 13/ One UI 5.1.1, Android 12/ One UI 4.1

### Affected device model

Samsung Galaxy Tab S7+, Samsung Galaxy S10

**Comment by hegocre** [comment]
Hello @JannikWilhelm 

I have installed the Samsung browser and checked, and indeed, it does not work. I've been investigating, and it looks like Samsung Internet has a whitelist of apps allowed to whitelist, which means that the request does not reach the autofill service at all. I'm sorry, but there is nothing I can do to solve this, this is a stupid Samsung policy that makes no sense, but then again, here we are...

Best regards
