### ISSUE TITLE
No PopUp for NextcloudPasswords on tablet with keyboard

### ISSUE THREAD

**Issue by xlemassacre** [hegocre/NextcloudPasswords#84]
### Checklist

- [X] I am able to reproduce the bug with the latest version [here](https://github.com/hegocre/NextcloudPasswords/releases/latest).
- [X] I have checked and there are *no existing issues* - [open](https://github.com/hegocre/NextcloudPasswords/issues) or [closed](https://github.com/hegocre/NextcloudPasswords/issues?q=is%3Aissue+is%3Aclosed) - which report the same bug.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.

### Affected version

v1.0.7

### Steps to reproduce the bug

1. open a website that has a username/password form
2. click in the username (or password) filed

### Expected behavior

as there is the keyboard connected via bluetooth, the virtual keyboard does not appear.
a popup over the username filed should apper (as shown in this image https://github.com/hegocre/NextcloudPasswords/issues/22#issuecomment-1849001665) 

### Actual behavior

no popup appears

### Affected Android/Custom ROM version

Android 13

### Affected device model

Galaxy Tab S7

### Additional information

when disconnecting the bluetooth keyboard the app works fine.
the virtual keyboard appears with a button to open nextcloud passwords

**Comment by hegocre** [comment]
Hello, and thank you for your feedback. I think I might know where is the problem. I will take a deeper look into it and see how to proceed.

Cheers!

**Comment by xlemassacre** [comment]
That would be nice if this can be fixed. I could test the fix if you need a verification

**Comment by hegocre** [comment]
Hello,

I've been investigating, and is there any chance that you are using the samsung keyboard? In that case, could you try to use another virtual keyboard (like gboard). Looks like that could be the problem.

Thank you!

**Comment by xlemassacre** [comment]
You are right, this is a problem with the samsung keyboard. I've install gboard now and it works with that keyboard!

Is this a problem of the samsung keyboard itself and can't be fixed on your side?

**Comment by hegocre** [comment]
Maybe I could try to implement some kind of workaround to see if the keyboard is actually showing, but I think the best option would be to allow the user to disable keyboard autofill, so ot always shows as a popup. Would that work for you?

**Comment by xlemassacre** [comment]
Yes that would also be a good option
