### ISSUE TITLE
Feature Request: Search On Username Option

### ISSUE THREAD

**Issue by Saijin-Naib** [hegocre/NextcloudPasswords#86]
### Checklist

- [X] I have checked and there are *no existing issues* - [open](https://github.com/hegocre/NextcloudPasswords/issues) or [closed](https://github.com/hegocre/NextcloudPasswords/issues?q=is%3Aissue+is%3Aclosed) - which request the same feature.
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.

### Feature description

An option to enable search and match on username. Maybe in Settings as some folks may not like it. 

### Why do you want this feature?

It helps massively when managing many accounts, especially where you know the username but not exact Name or first URL match. 

### Additional information

It would help match, for instance, wifeemail@domain across all entries so I can find her settings for RoundCube, instead of having to remember if I saved it from cPanel or RoundCube or the actual Webmail URI.

**Comment by hegocre** [comment]
Hello,

I have checked, and the web interface searches on username, so it makes sense to make it a default as well, specially when taking into account that I don't like to bloat the settings page. I will do it this way.

Thank you!

**Comment by mvozzo** [comment]
> Hello,
> 
> I have checked, and the web interface searches on username, so it makes sense to make it a default as well, specially when taking into account that I don't like to bloat the settings page. I will do it this way.
> 
> Thank you!

Hey @hegocre , I would think twice about making the feature the 'default'.

  I think it would be best to allow the user to decide if they prefer search to be prioritised on:
A) username , or
B) name

Thanks.
